package main

import (
	"context"
	"fmt"
	"html/template"
	"io"
	"io/fs"
	"log/slog"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync/atomic"
	"time"

	"golang.org/x/sync/errgroup"

	"github.com/monolithiclab/gomddoc/internal/config"
	"github.com/monolithiclab/gomddoc/internal/enricher"
	"github.com/monolithiclab/gomddoc/internal/locale"
	"github.com/monolithiclab/gomddoc/internal/metadata"
	"github.com/monolithiclab/gomddoc/internal/negotiate"
	"github.com/monolithiclab/gomddoc/internal/provider"
	"github.com/monolithiclab/gomddoc/internal/renderer"
	"github.com/monolithiclab/gomddoc/internal/resolve"
	"github.com/monolithiclab/gomddoc/internal/server"
	tmpl "github.com/monolithiclab/gomddoc/internal/template"
	"github.com/monolithiclab/gomddoc/internal/text"
)

// BuildCmd holds all flags for the build subcommand.
type BuildCmd struct {
	Dir    string `arg:"" optional:"" default:"." env:"GOMDDOC_SERVER_DIR" help:"Markdown source directory or Git URL."`
	Output string `name:"output" short:"o" default:"build/site" env:"GOMDDOC_BUILD_OUTPUT" help:"Output directory for generated static site."`
	Domain string `name:"domain" short:"d" default:"" env:"GOMDDOC_DOMAIN" help:"Override site domain for canonical URLs, sitemap, and SEO tags."`
}

// sentinelFile is the name of the marker file written to output directories
// created by gomddoc build. Its presence signals that the directory is safe
// to overwrite on subsequent builds.
const sentinelFile = ".gomddoc-build"

// buildStats tracks statistics for the build process.
// All fields use atomic types for safe concurrent updates during parallel builds.
type buildStats struct {
	markdownFiles atomic.Int64
	copiedFiles   atomic.Int64
	skippedFiles  atomic.Int64
	totalBytes    atomic.Int64
}

// buildContext holds shared dependencies for building files, eliminating
// parameter sprawl across walkAndBuild, buildFile, and copyFile.
type buildContext struct {
	registry         renderer.RendererRegistry
	enricherRegistry enricher.EnricherRegistry
	templateRenderer *tmpl.HTMLRenderer
	siteConfig       *config.SiteConfig
	bundle           *locale.Bundle
	languageInfos    []tmpl.LanguageInfo // shared across all pages (Active set per-walk)
	lang             string              // resolved language for this walk
	tFunc            func(string) string // translation function bound to lang
}

// Run executes the build command.
func (b *BuildCmd) Run() error {
	start := time.Now()

	if err := b.guardOutputDir(); err != nil {
		return err
	}

	if err := os.MkdirAll(b.Output, 0750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(filepath.Join(b.Output, sentinelFile), []byte("generated by gomddoc build\n"), 0644); err != nil { // #nosec G306
		return fmt.Errorf("write sentinel file: %w", err)
	}

	cfg, err := config.NewFromDir(b.Dir)
	if err != nil {
		return fmt.Errorf("build config: %w", err)
	}

	if b.Domain != "" {
		cfg.Site.Meta.Domain = b.Domain
		cfg.Site.Normalize()
		if err := cfg.Site.Validate(); err != nil {
			return fmt.Errorf("domain flag: %w", err)
		}
	}

	prov, err := provider.NewProvider(cfg.Server.Dir, cfg.Site.DefaultIndex, cfg.Site.DirIndex, cfg.Site.Exclude)
	if err != nil {
		return fmt.Errorf("build provider: %w", err)
	}
	defer func() {
		if closeErr := prov.Close(); closeErr != nil {
			slog.Error("Failed to close provider", slog.Any("error", closeErr))
		}
	}()

	lp, err := setupLanguagePipelines(cfg, prov, PipelineOptions{
		EnableCache:      true,
		EnableNavigation: true, // needed for prev/next page links
		EnableMetadata:   true, // needed for SEO and redirect generation
	})
	if err != nil {
		return fmt.Errorf("build pipeline: %w", err)
	}

	pipeline := lp.Default
	bundle := lp.Bundle
	detectedLangs := lp.Languages

	contentRoot, err := prov.RootFS(context.Background())
	if err != nil {
		return fmt.Errorf("build root fs: %w", err)
	}

	// Build language info for multi-language sites
	var languageInfos []tmpl.LanguageInfo
	if len(detectedLangs) > 0 {
		languageInfos = tmpl.BuildLanguageInfos(bundle, cfg.Site.Language, detectedLangs)
	}

	slog.Info("Building static site", slog.String("source", b.Dir), slog.String("output", b.Output))

	bc := &buildContext{
		registry:         pipeline.Registry,
		enricherRegistry: pipeline.EnricherRegistry,
		templateRenderer: pipeline.TemplateRenderer,
		siteConfig:       &cfg.Site,
		bundle:           bundle,
		languageInfos:    tmpl.WithActiveLang(languageInfos, cfg.Site.Language),
		lang:             cfg.Site.Language,
		tFunc:            bundle.TFunc(cfg.Site.Language),
	}

	stats, err := b.walkAndBuild(contentRoot, bc)
	if err != nil {
		return err
	}

	// Copy static assets to _assets/ directory in the output
	if pipeline.StaticFS != nil {
		if err := b.copyStaticAssets(pipeline.StaticFS, stats); err != nil {
			return fmt.Errorf("copy static assets: %w", err)
		}
	}

	// Generate SEO files (robots.txt and sitemap.xml)
	if err := b.generateSEOFiles(pipeline.MetaIndex, &cfg.Site, pipeline.Resolver, prov); err != nil {
		return fmt.Errorf("generate SEO files: %w", err)
	}

	// Generate redirect HTML files for redirect_from frontmatter
	if err := b.generateRedirectFiles(pipeline.MetaIndex, &cfg.Site, pipeline.Resolver); err != nil {
		return fmt.Errorf("generate redirect files: %w", err)
	}

	// Generate extension redirect files (e.g. guide.html -> guide/)
	if err := b.generateExtensionRedirects(pipeline.Resolver, cfg.Site.DefaultIndex); err != nil {
		return fmt.Errorf("generate extension redirects: %w", err)
	}

	// Generate 404.html for static host compatibility (Netlify, GitHub Pages, Cloudflare Pages)
	errorContent, err := b.renderErrorPage(http.StatusNotFound, bc)
	if err != nil {
		return fmt.Errorf("render 404 page: %w", err)
	}
	if err := b.writeOutputFile("404.html", errorContent); err != nil {
		return fmt.Errorf("write 404.html: %w", err)
	}

	// Build non-default languages into subdirectories
	for _, lang := range detectedLangs {
		langPipe := lp.ByLang[lang]

		langBC := &buildContext{
			registry:         bc.registry,
			enricherRegistry: bc.enricherRegistry,
			templateRenderer: bc.templateRenderer,
			siteConfig:       bc.siteConfig,
			bundle:           bundle,
			languageInfos:    tmpl.WithActiveLang(languageInfos, lang),
			lang:             lang,
			tFunc:            bundle.TFunc(lang),
		}

		langStats, langErr := b.walkAndBuildLang(contentRoot, langBC, lang)
		if langErr != nil {
			slog.Warn("Failed to build language", slog.String("lang", lang), slog.Any("error", langErr))
			continue
		}
		stats.markdownFiles.Add(langStats.markdownFiles.Load())
		stats.copiedFiles.Add(langStats.copiedFiles.Load())
		stats.totalBytes.Add(langStats.totalBytes.Load())

		// Generate per-language 404 page
		langErrorContent, langErrPage := b.renderErrorPage(http.StatusNotFound, langBC)
		if langErrPage != nil {
			slog.Warn("Failed to render 404 page for language", slog.String("lang", lang), slog.Any("error", langErrPage))
			continue
		}
		if langWriteErr := b.writeOutputFile(path.Join(lang, "404.html"), langErrorContent); langWriteErr != nil {
			slog.Warn("Failed to write 404 page for language", slog.String("lang", lang), slog.Any("error", langWriteErr))
		}

		// Generate per-language sitemap and feed
		if langPipe != nil && langPipe.MetaIndex != nil && cfg.Site.Meta.Domain != "" {
			langSitemapData, sErr := server.GenerateSitemap(context.Background(), langPipe.MetaIndex, cfg.Site.Meta.Domain, cfg.Site.DefaultIndex, langPipe.Provider, langPipe.Resolver, "/"+lang)
			if sErr != nil {
				slog.Warn("Failed to generate sitemap for language", slog.String("lang", lang), slog.Any("error", sErr))
			} else if wErr := b.writeOutputFile(path.Join(lang, "sitemap.xml"), langSitemapData); wErr != nil {
				slog.Warn("Failed to write sitemap for language", slog.String("lang", lang), slog.Any("error", wErr))
			}

			langFeedData, fErr := server.GenerateFeed(context.Background(), langPipe.MetaIndex, cfg.Site.Meta.Domain, cfg.Site.DefaultIndex, langPipe.Provider, cfg.Site.Meta.Title, langPipe.Resolver, "/"+lang)
			if fErr != nil {
				slog.Warn("Failed to generate feed for language", slog.String("lang", lang), slog.Any("error", fErr))
			} else if wErr := b.writeOutputFile(path.Join(lang, "feed.xml"), langFeedData); wErr != nil {
				slog.Warn("Failed to write feed for language", slog.String("lang", lang), slog.Any("error", wErr))
			}
		}
	}

	// Generate sitemap-index.xml when multiple languages exist
	if len(detectedLangs) > 0 && cfg.Site.Meta.Domain != "" {
		var sitemapIndex strings.Builder
		sitemapIndex.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
		sitemapIndex.WriteString(`<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">` + "\n")
		sitemapIndex.WriteString(`  <sitemap><loc>https://` + cfg.Site.Meta.Domain + `/sitemap.xml</loc></sitemap>` + "\n")
		for _, lang := range detectedLangs {
			sitemapIndex.WriteString(`  <sitemap><loc>https://` + cfg.Site.Meta.Domain + `/` + lang + `/sitemap.xml</loc></sitemap>` + "\n")
		}
		sitemapIndex.WriteString(`</sitemapindex>` + "\n")

		if err := b.writeOutputFile("sitemap-index.xml", []byte(sitemapIndex.String())); err != nil {
			return fmt.Errorf("write sitemap-index.xml: %w", err)
		}
	}

	elapsed := time.Since(start)
	slog.Info("Build complete",
		slog.Int64("markdown_files", stats.markdownFiles.Load()),
		slog.Int64("copied_files", stats.copiedFiles.Load()),
		slog.Int64("skipped_files", stats.skippedFiles.Load()),
		slog.Int64("total_bytes", stats.totalBytes.Load()),
		slog.Duration("elapsed", elapsed),
	)

	return nil
}

// guardOutputDir checks whether the output directory already exists.
// If it is non-empty, the sentinel file (.gomddoc-build) must be present
// to prove it was created by a previous build. Without the sentinel, the
// build refuses to proceed to prevent accidental deletion of unrelated files.
func (b *BuildCmd) guardOutputDir() error {
	info, err := os.Stat(b.Output)
	if err != nil {
		return nil // does not exist — nothing to guard
	}
	if !info.IsDir() {
		return fmt.Errorf("output path %q exists but is not a directory", b.Output)
	}

	empty, err := isDirEmpty(b.Output)
	if err != nil {
		return fmt.Errorf("check output directory: %w", err)
	}
	if empty {
		return nil
	}

	// Non-empty directory: require sentinel file
	si, err := os.Stat(filepath.Join(b.Output, sentinelFile))
	if err != nil || si.IsDir() {
		return fmt.Errorf("output directory %q is not empty and was not created by gomddoc build; refusing to overwrite", b.Output)
	}

	if err := os.RemoveAll(b.Output); err != nil {
		return fmt.Errorf("remove existing output directory: %w", err)
	}
	slog.Info("Removed existing output directory", slog.String("path", b.Output))
	return nil
}

// isDirEmpty reports whether directory at path contains no entries.
func isDirEmpty(path string) (bool, error) {
	f, err := os.Open(path) // #nosec G304 -- path is output dir controlled by user via CLI
	if err != nil {
		return false, err
	}
	defer f.Close()

	_, err = f.Readdirnames(1)
	if err == io.EOF {
		return true, nil
	}
	return false, err
}

// walkAndBuild walks the content root and generates the static site.
func (b *BuildCmd) walkAndBuild(contentRoot fs.FS, bc *buildContext) (*buildStats, error) {
	return b.walkAndBuildToDir(contentRoot, bc, "")
}

// walkAndBuildLang builds a single non-default language into its subdirectory.
func (b *BuildCmd) walkAndBuildLang(contentRoot fs.FS, bc *buildContext, lang string) (*buildStats, error) {
	langFS, err := fs.Sub(contentRoot, lang)
	if err != nil {
		return nil, fmt.Errorf("create sub-FS for language %s: %w", lang, err)
	}
	return b.walkAndBuildToDir(langFS, bc, lang)
}

// walkAndBuildToDir is the shared implementation for walkAndBuild and walkAndBuildLang.
// When outputPrefix is non-empty, all output files are written under that subdirectory.
func (b *BuildCmd) walkAndBuildToDir(contentRoot fs.FS, bc *buildContext, outputPrefix string) (*buildStats, error) {
	stats := &buildStats{}

	var filePaths []string
	dirsWithIndexMD := make(map[string]bool)
	err := fs.WalkDir(contentRoot, ".", func(filePath string, d fs.DirEntry, err error) error {
		if err != nil {
			return fmt.Errorf("walk %s: %w", filePath, err)
		}

		if skip, skipErr := provider.SkipWalkEntry(filePath, d.Name(), d.IsDir(), bc.siteConfig.Exclude); skip {
			if !d.IsDir() {
				stats.skippedFiles.Add(1)
			}
			return skipErr
		}

		if !d.IsDir() {
			filePaths = append(filePaths, filePath)
			if strings.EqualFold(d.Name(), "index.md") {
				dirsWithIndexMD[path.Dir(filePath)] = true
			}
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	g, ctx := errgroup.WithContext(context.Background())
	g.SetLimit(runtime.NumCPU())

	htmlAccept := []negotiate.MediaType{{Type: "text", Subtype: "html", Q: 1.0}}

	for _, fp := range filePaths {
		g.Go(func() error {
			mimeType := negotiate.DetectMIME(fp)
			normalized := negotiate.NormalizeMimeType(mimeType)

			contentRenderer, _, err := bc.registry.Get(normalized, htmlAccept)
			if err != nil {
				return b.copyFile(contentRoot, fp, outputPrefix, stats)
			}
			return b.buildFile(ctx, contentRoot, fp, contentRenderer, normalized, bc, dirsWithIndexMD, outputPrefix, stats)
		})
	}

	if err := g.Wait(); err != nil {
		return nil, err
	}

	return stats, nil
}

// buildFile renders a file to HTML and writes it to the output directory.
// When outputPrefix is non-empty, the output path is prefixed with it
// (e.g., "fr" produces "fr/page/index.html").
func (b *BuildCmd) buildFile(
	ctx context.Context,
	contentRoot fs.FS,
	filePath string,
	contentRenderer renderer.ContentRenderer,
	mimeType string,
	bc *buildContext,
	dirsWithIndexMD map[string]bool,
	outputPrefix string,
	stats *buildStats,
) error {
	content, err := fs.ReadFile(contentRoot, filePath)
	if err != nil {
		return fmt.Errorf("read %s: %w", filePath, err)
	}

	enrichment, err := bc.enricherRegistry.Get(mimeType).Enrich(ctx, content, "/"+filePath)
	if err != nil {
		return fmt.Errorf("enrich %s: %w", filePath, err)
	}

	renderResult, err := contentRenderer.Render(ctx, content, enrichment)
	if err != nil {
		return fmt.Errorf("render %s: %w", filePath, err)
	}

	metadata := enrichment.Metadata
	if metadata == nil {
		metadata = make(map[string]any)
	}
	if _, ok := metadata["title"]; !ok {
		metadata["title"] = text.DeriveTitle("/" + filePath)
	}

	templateCtx := &tmpl.TemplateContext{
		Site: bc.siteConfig,
		Page: tmpl.PageContext{
			Content:    template.HTML(renderResult.Content), // #nosec G203
			Path:       "/" + filePath,
			Meta:       metadata,
			Features:   config.MergeFeatures(bc.siteConfig.Theme.Features, enrichment.Features),
			TOC:        enrichment.TOC,
			Navigation: enrichment.Navigation,
			PrevPage:   enrichment.PrevPage,
			NextPage:   enrichment.NextPage,
		},
	}
	templateCtx.WithI18n(bc.lang, bc.tFunc, bc.languageInfos)

	templateName := tmpl.ResolveLayout(bc.templateRenderer, metadata)
	rendered, err := bc.templateRenderer.Render(ctx, templateName, templateCtx)
	if err != nil {
		return fmt.Errorf("template render %s: %w", filePath, err)
	}

	var htmlPath string
	if len(bc.siteConfig.StripExtensions) > 0 {
		htmlPath = prettyOutputPath(filePath, bc.siteConfig.DefaultIndex, dirsWithIndexMD)
	} else {
		htmlPath = strings.TrimSuffix(filePath, path.Ext(filePath)) + ".html"
		if server.IsDefaultIndex(filePath, bc.siteConfig.DefaultIndex) && !dirsWithIndexMD[path.Dir(filePath)] {
			htmlPath = path.Join(path.Dir(filePath), "index.html")
		}
	}
	outPath := htmlPath
	if outputPrefix != "" {
		outPath = path.Join(outputPrefix, htmlPath)
	}
	if err := b.writeOutputFile(outPath, rendered); err != nil {
		return err
	}
	stats.totalBytes.Add(int64(len(rendered)))

	stats.markdownFiles.Add(1)
	slog.Debug("Built", slog.String("file", filePath), slog.String("output", outPath))

	return nil
}

// copyFile copies a non-markdown file to the output directory as-is.
// When outputPrefix is non-empty, the file is written under that subdirectory.
func (b *BuildCmd) copyFile(contentRoot fs.FS, filePath, outputPrefix string, stats *buildStats) error {
	content, err := fs.ReadFile(contentRoot, filePath)
	if err != nil {
		return fmt.Errorf("read %s: %w", filePath, err)
	}

	outPath := filePath
	if outputPrefix != "" {
		outPath = path.Join(outputPrefix, filePath)
	}
	if err := b.writeOutputFile(outPath, content); err != nil {
		return err
	}

	stats.copiedFiles.Add(1)
	stats.totalBytes.Add(int64(len(content)))
	slog.Debug("Copied", slog.String("file", filePath))

	return nil
}

// copyStaticAssets walks the static filesystem and copies all files to the _assets/ output directory.
func (b *BuildCmd) copyStaticAssets(staticFS fs.FS, stats *buildStats) error {
	return fs.WalkDir(staticFS, ".", func(filePath string, d fs.DirEntry, err error) error {
		if err != nil {
			return fmt.Errorf("walk static %s: %w", filePath, err)
		}
		if d.IsDir() {
			return nil
		}

		content, readErr := fs.ReadFile(staticFS, filePath)
		if readErr != nil {
			return fmt.Errorf("read static %s: %w", filePath, readErr)
		}

		outPath := path.Join("_assets", filePath)
		if writeErr := b.writeOutputFile(outPath, content); writeErr != nil {
			return writeErr
		}

		stats.copiedFiles.Add(1)
		stats.totalBytes.Add(int64(len(content)))
		slog.Debug("Copied static asset", slog.String("file", outPath))
		return nil
	})
}

// generateSEOFiles generates robots.txt and optionally sitemap.xml in the output directory.
func (b *BuildCmd) generateSEOFiles(idx *metadata.Index, siteConfig *config.SiteConfig, resolver *resolve.PathResolver, prov provider.Provider) error {
	// Always generate robots.txt
	robotsTxt := server.GenerateRobotsTxt(siteConfig.Meta.Domain)
	if err := b.writeOutputFile("robots.txt", []byte(robotsTxt)); err != nil {
		return fmt.Errorf("write robots.txt: %w", err)
	}
	slog.Debug("Generated", slog.String("file", "robots.txt"))

	// Generate sitemap.xml only if domain is configured
	if siteConfig.Meta.Domain != "" {
		sitemapData, err := server.GenerateSitemap(context.Background(), idx, siteConfig.Meta.Domain, siteConfig.DefaultIndex, prov, resolver, "")
		if err != nil {
			return fmt.Errorf("generate sitemap: %w", err)
		}

		if err := b.writeOutputFile("sitemap.xml", sitemapData); err != nil {
			return fmt.Errorf("write sitemap.xml: %w", err)
		}
		slog.Debug("Generated", slog.String("file", "sitemap.xml"))

		feedData, err := server.GenerateFeed(context.Background(), idx, siteConfig.Meta.Domain, siteConfig.DefaultIndex, prov, siteConfig.Meta.Title, resolver, "")
		if err != nil {
			return fmt.Errorf("generate feed: %w", err)
		}

		if err := b.writeOutputFile("feed.xml", feedData); err != nil {
			return fmt.Errorf("write feed.xml: %w", err)
		}
		slog.Debug("Generated", slog.String("file", "feed.xml"))
	}

	return nil
}

// generateRedirectFiles builds redirect HTML files from redirect_from frontmatter.
func (b *BuildCmd) generateRedirectFiles(idx *metadata.Index, siteConfig *config.SiteConfig, resolver *resolve.PathResolver) error {
	redirects := server.BuildRedirectMap(idx, resolver)
	if len(redirects) == 0 {
		return nil
	}

	for source, target := range redirects {
		html := server.GenerateRedirectHTML(target)
		// Write as source/index.html so the URL matches without extension
		outPath := strings.TrimPrefix(source, "/")
		if outPath == "" {
			continue
		}
		if !strings.Contains(path.Base(outPath), ".") {
			outPath = path.Join(outPath, "index.html")
		}
		if err := b.writeOutputFile(outPath, html); err != nil {
			return fmt.Errorf("write redirect %s: %w", source, err)
		}
		slog.Debug("Generated redirect", slog.String("from", source), slog.String("to", target))
	}

	return nil
}

// prettyOutputPath computes the output path for pretty URLs.
// Regular files: guide.md -> guide/index.html
// index.md stays as index.html (no double nesting)
// Default index (README.md) -> index.html when no index.md in same dir
func prettyOutputPath(filePath, defaultIndex string, dirsWithIndexMD map[string]bool) string {
	base := path.Base(filePath)

	// index.md stays as index.html — no double nesting
	if strings.EqualFold(base, "index.md") {
		return strings.TrimSuffix(filePath, path.Ext(filePath)) + ".html"
	}

	// Default index (README.md) becomes index.html when no index.md exists
	if strings.EqualFold(base, defaultIndex) && !dirsWithIndexMD[path.Dir(filePath)] {
		return path.Join(path.Dir(filePath), "index.html")
	}

	// Regular file: guide.md -> guide/index.html
	stem := strings.TrimSuffix(filePath, path.Ext(filePath))
	return path.Join(stem, "index.html")
}

// generateExtensionRedirects generates HTML redirect files so old extension-based
// URLs still work on static hosts (e.g. guide.html -> guide/).
// Default index files (e.g., README.md) are skipped — their URL is the
// directory path, not the extensionless form.
func (b *BuildCmd) generateExtensionRedirects(resolver *resolve.PathResolver, defaultIndex string) error {
	if resolver == nil || resolver.IsEmpty() {
		return nil
	}

	for realPath, cleanPath := range resolver.AllMappings() {
		if server.IsDefaultIndex(realPath, defaultIndex) {
			continue
		}
		html := server.GenerateRedirectHTML("/" + cleanPath)
		if err := b.writeOutputFile(realPath, html); err != nil {
			return fmt.Errorf("write extension redirect %s: %w", realPath, err)
		}
		slog.Debug("Generated extension redirect",
			slog.String("from", "/"+realPath),
			slog.String("to", "/"+cleanPath),
		)
	}

	return nil
}

// writeOutputFile writes content to a file in the output directory, creating parent directories as needed.
func (b *BuildCmd) writeOutputFile(relPath string, content []byte) error {
	// Reject absolute paths early (before filepath.Join).
	// On Unix, filepath.IsAbs checks for leading "/".
	// On Windows, it checks for drive letters and UNC paths.
	if filepath.IsAbs(relPath) {
		return fmt.Errorf("path %q escapes outside output directory", relPath)
	}

	outPath := filepath.Join(b.Output, relPath)

	// Resolve to absolute paths and verify containment.
	absOutput, err := filepath.Abs(b.Output)
	if err != nil {
		return fmt.Errorf("resolve output directory: %w", err)
	}
	absOut, err := filepath.Abs(outPath)
	if err != nil {
		return fmt.Errorf("resolve output path: %w", err)
	}
	if !strings.HasPrefix(absOut, absOutput+string(filepath.Separator)) && absOut != absOutput {
		return fmt.Errorf("path %q escapes outside output directory", relPath)
	}

	dir := filepath.Dir(outPath)
	if err := os.MkdirAll(dir, 0750); err != nil {
		return fmt.Errorf("create directory %s: %w", dir, err)
	}

	if err := os.WriteFile(outPath, content, 0644); err != nil { // #nosec G306
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	return nil
}

// renderErrorPage renders an error page through the template engine.
func (b *BuildCmd) renderErrorPage(statusCode int, bc *buildContext) ([]byte, error) {
	statusTitle := http.StatusText(statusCode)

	ctx := &tmpl.TemplateContext{
		Site: bc.siteConfig,
		Page: tmpl.PageContext{
			Path: "/" + strconv.Itoa(statusCode),
			Meta: map[string]any{
				"title":         statusTitle,
				"robots":        "noindex",
				"error_code":    statusCode,
				"error_title":   statusTitle,
				"error_message": server.StatusMessage(statusCode),
			},
			Features: config.MergeFeatures(bc.siteConfig.Theme.Features),
		},
	}
	ctx.WithI18n(bc.lang, bc.tFunc, nil)

	return bc.templateRenderer.Render(context.Background(), "error.html.tmpl", ctx)
}
