# gomddoc site configuration
# See: https://github.com/monolithiclab/gomddoc

default_index: README.md
dir_index: false
meta:
  title: Testsite
  description: ""
theme:
  name: default
  features:
    color_chips: true
highlighting:
  theme: github
